#!/usr/bin/env bash
from="$1"
rarity="$2"
# Definition of the power runes. The actual meaning is given to these
# in the runecraft code. The format is:
# name:sval:lvl:rarity:pval:color
echo "
Wood	0	1	1	1	w
Copper	1	5	1	3	w
Iron	2	10	1	6	w
Moonstone	3	15	1	10	w
Silver	4	20	1	15	w
Gold	5	35	2	20	w
Mithril	6	50	2	30	w
Adamantite	7	70	5	50	w
" | awk -F '	' '/^[^#]/{
	if(NF) {
		n=++i+'$from'
		printf("\n")
		printf("N:%d:%s\n",n,$1)
		printf("G:%%:%s\n",$6)
		printf("I:107:%d:%d\n",$2,$5)
		printf("W:%d:0:2:%d\n",$3,$3*50)
		printf("A:%d/%d\n",$3,$4*'$rarity')
		printf("P:0:1d1:0:0:0\n")
		printf("F:SPELL\n")
	}
}'
